[env:esp32h2-dev]
platform = https://github.com/platformio/platform-espressif32.git#develop
platform_packages =
    platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.2
    platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.2/esp32-arduino-libs-3.0.2.zip
    espressif/toolchain-riscv32-esp @ 12.2.0+20230208
board = esp32h2-dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = default.csv
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
